"""fix missing bank_connections table

Revision ID: 18acf8fd6684
Revises: 20a7661b51e5
Create Date: 2025-08-13 17:29:26.874610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18acf8fd6684'
down_revision = '20a7661b51e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
